Add jaxb and jakarta deps
Both the notice plugin and the PPTX thumbnailer require JAXB.
It was present in the default JDK in java 8, but by java 11 has
been pulled out and needs to be depended upon explicitly. See
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception